/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Solution = IDL.Record({
  'organicSolutions' : IDL.Text,
  'causes' : IDL.Text,
  'chemicalSolutions' : IDL.Text,
  'preventiveMeasures' : IDL.Text,
  'treatmentSteps' : IDL.Text,
});
export const Location = IDL.Record({
  'latitude' : IDL.Float64,
  'longitude' : IDL.Float64,
});
export const DiagnosisSession = IDL.Record({
  'id' : IDL.Nat,
  'soilType' : IDL.Text,
  'crop' : IDL.Text,
  'user' : IDL.Principal,
  'solution' : Solution,
  'timestamp' : IDL.Int,
  'symptoms' : IDL.Text,
  'image' : IDL.Opt(ExternalBlob),
  'location' : Location,
});
export const FarmingTip = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'timestamp' : IDL.Int,
  'category' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addImageToDiagnosis' : IDL.Func([IDL.Nat, ExternalBlob], [], []),
  'addLocation' : IDL.Func([IDL.Text, IDL.Float64, IDL.Float64], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllDiagnosisSessions' : IDL.Func(
      [],
      [IDL.Vec(DiagnosisSession)],
      ['query'],
    ),
  'getAllFarmingTips' : IDL.Func([], [IDL.Vec(FarmingTip)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDiagnosisSession' : IDL.Func([IDL.Nat], [DiagnosisSession], ['query']),
  'getDiagnosisSessionsByUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(DiagnosisSession)],
      ['query'],
    ),
  'getFarmingTipsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(FarmingTip)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'submitDiagnosis' : IDL.Func(
      [
        IDL.Record({
          'soilType' : IDL.Text,
          'crop' : IDL.Text,
          'suggestion' : Solution,
          'locationId' : IDL.Text,
          'symptoms' : IDL.Text,
        }),
      ],
      [IDL.Nat],
      [],
    ),
  'submitFarmingTip' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Solution = IDL.Record({
    'organicSolutions' : IDL.Text,
    'causes' : IDL.Text,
    'chemicalSolutions' : IDL.Text,
    'preventiveMeasures' : IDL.Text,
    'treatmentSteps' : IDL.Text,
  });
  const Location = IDL.Record({
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
  });
  const DiagnosisSession = IDL.Record({
    'id' : IDL.Nat,
    'soilType' : IDL.Text,
    'crop' : IDL.Text,
    'user' : IDL.Principal,
    'solution' : Solution,
    'timestamp' : IDL.Int,
    'symptoms' : IDL.Text,
    'image' : IDL.Opt(ExternalBlob),
    'location' : Location,
  });
  const FarmingTip = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'timestamp' : IDL.Int,
    'category' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addImageToDiagnosis' : IDL.Func([IDL.Nat, ExternalBlob], [], []),
    'addLocation' : IDL.Func([IDL.Text, IDL.Float64, IDL.Float64], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllDiagnosisSessions' : IDL.Func(
        [],
        [IDL.Vec(DiagnosisSession)],
        ['query'],
      ),
    'getAllFarmingTips' : IDL.Func([], [IDL.Vec(FarmingTip)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDiagnosisSession' : IDL.Func([IDL.Nat], [DiagnosisSession], ['query']),
    'getDiagnosisSessionsByUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(DiagnosisSession)],
        ['query'],
      ),
    'getFarmingTipsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(FarmingTip)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'submitDiagnosis' : IDL.Func(
        [
          IDL.Record({
            'soilType' : IDL.Text,
            'crop' : IDL.Text,
            'suggestion' : Solution,
            'locationId' : IDL.Text,
            'symptoms' : IDL.Text,
          }),
        ],
        [IDL.Nat],
        [],
      ),
    'submitFarmingTip' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };