/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DiagnosisSession {
  'id' : bigint,
  'soilType' : string,
  'crop' : string,
  'user' : Principal,
  'solution' : Solution,
  'timestamp' : bigint,
  'symptoms' : string,
  'image' : [] | [ExternalBlob],
  'location' : Location,
}
export type ExternalBlob = Uint8Array;
export interface FarmingTip {
  'title' : string,
  'content' : string,
  'timestamp' : bigint,
  'category' : string,
}
export interface Location { 'latitude' : number, 'longitude' : number }
export interface Solution {
  'organicSolutions' : string,
  'causes' : string,
  'chemicalSolutions' : string,
  'preventiveMeasures' : string,
  'treatmentSteps' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addImageToDiagnosis' : ActorMethod<[bigint, ExternalBlob], undefined>,
  'addLocation' : ActorMethod<[string, number, number], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllDiagnosisSessions' : ActorMethod<[], Array<DiagnosisSession>>,
  'getAllFarmingTips' : ActorMethod<[], Array<FarmingTip>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDiagnosisSession' : ActorMethod<[bigint], DiagnosisSession>,
  'getDiagnosisSessionsByUser' : ActorMethod<
    [Principal],
    Array<DiagnosisSession>
  >,
  'getFarmingTipsByCategory' : ActorMethod<[string], Array<FarmingTip>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'submitDiagnosis' : ActorMethod<
    [
      {
        'soilType' : string,
        'crop' : string,
        'suggestion' : Solution,
        'locationId' : string,
        'symptoms' : string,
      },
    ],
    bigint
  >,
  'submitFarmingTip' : ActorMethod<[string, string, string], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];